"""Railway's Infrastructure-as-Code file — the actual, authoritative
source for this project's Railway configuration (start command, domains,
the Postgres database + its storage volume, which env vars exist without
exposing their values via preserve()). Railway's builder (Railpack) reads
this directly; it does NOT read the Procfile in this project, despite
Procfile being the more commonly documented convention — that mismatch is
exactly why an earlier attempt to add startup flags via the Procfile
silently had no effect (confirmed via `railway ssh` + /proc/1/cmdline).

Generated by `railway config pull` (which reads Railway's actual current
state) rather than written by hand, specifically to avoid the failure
mode of a hand-written file: applying an incomplete declaration deletes
whatever real Railway state it doesn't mention — an earlier draft of this
file (before pull) would have deleted every production secret and
disconnected the GitHub integration had it been applied. Preview any
future edit with `railway config plan` before ever running `apply`.

Requires `pip install railway-sdk` (a Railway CLI companion package, not
a project dependency — not in requirements.txt) to run `railway config
plan`/`apply` locally.
"""

from railway_sdk import define_railway, github, postgres, preserve, project, service, volume


@define_railway
def main(ctx=None):
    Postgres = postgres("Postgres", region="sfo")
    postgres_volume = volume(
        "postgres-volume",
        alerts={"usage": {"100": {}, "80": {}, "95": {}}},
        allowOnlineResize=True,
        region="sfo",
        sizeMB=5000,
    )
    web = service(
        "web",
        source=github("Kofi-Astro/Ushering", branch="master", checkSuites=False),
        start="uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=\"*\"",
        replicas={"sfo": 1},
        domains=["admin.gpsusheringandevents.com", "gpsusheringandevents.com"],
        env={
            "ADMIN_HOSTNAME": preserve(),
            "ADMIN_PASSWORD": preserve(),
            "DATABASE_URL": preserve(),
            "SECRET_KEY": preserve(),
        },
    )
    return project("adaptable-truth", resources=[Postgres, web, postgres_volume])
