"""Railway's Infrastructure-as-Code file — the actual, authoritative
source for this project's Railway configuration (start command, domains,
the Postgres database + its storage volume, the web service's own
persistent volume for uploaded photos, which env vars exist without
exposing their values via preserve()). Railway's builder (Railpack) reads
this directly; it does NOT read the Procfile in this project, despite
Procfile being the more commonly documented convention — that mismatch is
exactly why an earlier attempt to add startup flags via the Procfile
silently had no effect (confirmed via `railway ssh` + /proc/1/cmdline).

Normally regenerated by `railway config pull` (which reads Railway's
actual current state) rather than written by hand, specifically to avoid
the failure mode of a hand-written file: applying an incomplete
declaration deletes whatever real Railway state it doesn't mention — an
earlier draft of this file (before pull) would have deleted every
production secret and disconnected the GitHub integration had it been
applied. Preview any future edit with `railway config plan` before ever
running `apply`.

One caveat learned the hard way: the CLI version that generated this
file's most recent `config pull` (v5.45.10) emitted JS-style object
literals for the volume config dicts — bare unquoted keys like
`{ alerts: {...} }` — which is syntactically parseable Python (a dict
literal can use any expression as a key) but raises a NameError the
instant it's actually executed, since `alerts` isn't a defined variable
anywhere. Confirmed directly: `ast.parse` accepted it, but calling
`main()` failed immediately. This file has been hand-corrected back to
real Python dict syntax (quoted string keys). If a future `config pull`
overwrites this file again, run it through `python3 -c "import ...;
railway.main()"` (or equivalent) before trusting it — don't assume a
regenerated file is valid just because it parses.

Requires `pip install railway-sdk` (a Railway CLI companion package, not
a project dependency — not in requirements.txt) to run `railway config
plan`/`apply` locally.
"""

from railway_sdk import define_railway, github, postgres, preserve, project, service, volume


@define_railway
def main(ctx=None):
    Postgres = postgres("Postgres", region="sfo")
    web_volume = volume(
        "web-volume",
        alerts={"usage": {"100": {}, "80": {}, "95": {}}},
        allowOnlineResize=True,
        region="sfo",
        sizeMB=5000,
    )
    postgres_volume = volume(
        "postgres-volume",
        alerts={"usage": {"100": {}, "80": {}, "95": {}}},
        allowOnlineResize=True,
        region="sfo",
        sizeMB=5000,
    )
    web = service(
        "web",
        source=github("Kofi-Astro/Ushering", branch="master", checkSuites=False),
        start="uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=\"*\"",
        replicas={"sfo": 1},
        domains=["admin.gpsusheringandevents.com", "gpsusheringandevents.com"],
        # Persists uploaded gallery photos across redeploys — see
        # app/admin/routers/gallery.py's UPLOAD_DIR. Without this, every
        # deploy gets a fresh, empty container filesystem and silently
        # wipes whatever was uploaded since the last one (confirmed: this
        # happened to all 8 of the business owner's uploaded video poster
        # photos before this volume existed).
        volumeMounts={"/app/images/uploads": web_volume},
        env={
            "ADMIN_HOSTNAME": preserve(),
            "ADMIN_PASSWORD": preserve(),
            "DATABASE_URL": preserve(),
            "SECRET_KEY": preserve(),
        },
    )
    return project("adaptable-truth", resources=[Postgres, web, web_volume, postgres_volume])
